  <body>
    <section style="padding-top: 66px">
      <div class="jumbotron container text-center">
        <div class="card-columns">
          <div class="container">
          
          <a href="/imoveis_para_avaliar">
            <div class="card">
              <div class="card-body">                
                <div class="card-title text-dark">
                  Imóveis Pendentes
                  <span class="badge badge-primary"><?= $this->view->qtdImoveis ?></span>
                </div>
              </div>
            </div>
          </a>  

          <a href="/visitas_marcadas">
            <div class="card">
              <div class="card-body">
                <div class="card-title text-dark">Visitas Marcadas
                  <span class="badge badge-primary"><?= $this->view->visitas ?></span>
                </div>
              </div>
            </div>
          </a>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Mais Opções</div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>