<section style="padding-top: 80px;" class="container">
	<h3>Avaliar Imovel</h3>
</section>

<section>

  <div class="container jumbotron" style="border-color: black">
    <div>
      <div class="row mb-5">
        <div class="col-lg-6">
          <h5>Proprietário: </h5>
          <h5>Tipo do imóvel: <?= $this->view->imovel['tipo'] ?></h5>
          <h5>Status: <?= $this->view->imovel['status'] ?></h5>
        </div>
        <div class="col-lg-6">
          <h5>Endereço: <?= $this->view->imovel['endereco'] ?></h5>
          <h5>Número: <?= $this->view->imovel['numero'] ?></h5>
          <h5>Bairro: <?= $this->view->imovel['bairro'] ?></h5>
          <h5>CEP: <?= $this->view->imovel['cep'] ?></h5>
        </div>
      </div>

      <div class="row mb-5">
        <div class="col-lg-6">
          <h5>Área útil<?= $this->view->imovel['area_util'] ?></h5>
          <h5>Área total<?= $this->view->imovel['area_total'] ?></h5>
        </div>

        <div class="col-lg-6">
          <h5>Qtd. quartos: <?= $this->view->imovel['quartos'] ?></h5>
          <h5>Qtd. banheiros: <?= $this->view->imovel['banheiros'] ?></h5>
          <h5>Qtd. garagens: <?= $this->view->imovel['garagens'] ?></h5>
          <h5>Qtd. suítes: <?= $this->view->imovel['suites'] ?></h5>
        </div>
      </div>

      <div class="row">
      <div class="col-lg-6">
        <div class="row">
          <h5 class="container">Descriçãodo imóvel: </h5>  
        </div>
        <div class="row container jumbotron border border-dark">
          <?= $this->view->imovel['tipo'] ?>
        </div>      
      </div>
      <div class="col-lg-6">
        <h4>Valor: R$<?= $this->view->imovel['valor'] ?></h4>
      </div>
      </div>
    </div>
  </div>
</section>


<section class="container jumbotron">
  <h3 class="text-center">Agendar Visita</h3>
  <hr>
  <form action="/acao_cor?acao=agendar_visita&id_imovel=<?=$this->view->imovel['id']?>" method="post">
    <div class="form-group row">
      <label for="example-datetime-local-input" class="col-3 col-form-label">Selecione data e hora:</label>
      <div class="col-9">
        <input name="data" class="form-control" type="datetime-local" id="example-datetime-local-input">
      </div>
    </div>
    <div class="clearfix">
    <button type="submit" class="btn btn-success btn-lg float-right">Agendar Visitar</button>
    </div>
  </form>
  <hr>
  
</section>