<html>
	<head>
		<meta charset="utf-8" />
		<title>La Rede</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.min.js"></script>

		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/estilo.css">

		<script type="text/javascript">
			$(document).ready(function(){
				
			});
		</script>

	</head>

	<body>

		<header>
	      <nav class="navbar navbar-expand-sm navbar-light fixed-top bg-warning">
	        <div class="container">
	          <a href="/timeline" class="navbar-brand">
	            <i class="fab fa-accusoft fa-2x text-light"></i>
	          </a>
	          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
	            <!--<span class="navbar-toggler-icon"></span>-->
	            <i class="fas fa-bars text-white"></i>
	          </button>
	          <div id="nav-principal" class="collapse navbar-collapse">
	            <ul class="navbar-nav ml-auto">
	              <li class="nav-item">
	                <a href="/timeline" class="nav-link">Home</a>
	              </li>

	              <li class="nav-item">
	                <a href="/cadastrar_imovel" class="nav-link">Vender Imóvel</a>
	              </li>

	              <li class="nav-item">
	                <a href="/meus_imoveis" class="nav-link">Meus Imóveis</a>
	              </li>

	            <?php if($this->view->corretor == 1) { ?>
	              <li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          Modulo
			        </a>
			        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			          <a class="dropdown-item" href="/timeline">Comprador/Vendedor</a>
			          <a class="dropdown-item" href="/dashboardC">Corretor</a>
			      </li>
			  	<?php } ?>

	              <li class="nav-item">
	                <a href="" class="nav-link text-danger">Favoritos</a>
	              </li>
	              <li class="nav-item">
	                <a href="" class="nav-link text-danger">Interesse de compra</a>
	              </li>
	              <li class="nav-item">
	              <li class="nav-item">
	                <a href="/sair" class="nav-link">Sair</a>
	              </li>
	            </ul>
	            
	            <span class="navbar-text ml-2">
				  | Olá Sr(a) <?= $this->view->nome ?>
				</span>
              	<div class="media align-self-center">
				  <img class="mr-3 ml-2 rounded-circle" style="width: 50px; height: 50px" src="<?= $this->view->imagem_perfil ?>">
				</div>
	            
	          </div>
	        </div>
	      </nav>
	    </header>

		<?= $this->content() ?>

		<footer class="mt-4 mb-4">
	      <div class="container">
	        <div class="row">
	          <div class="col-md-8">
	            <p>
	              <a href="/timeline">Home</a>
	              <a href="/error_notfound">Recursos</a>
	              <a href="/error_notfound">Beneficios</a>
	              <a href="/error_notfound">Preços</a>
	            </p>
	          </div>
	          <div class="col-md-4 d-flex justify-content-end">
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-facebook"></i>
	            </a>
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-twitter"></i>
	            </a>
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-youtube"></i>
	            </a>
	          </div>
	        </div>
	      </div>
	    </footer>
	    
	</body>

</html>