<html>
	<head>
		<meta charset="utf-8" />
		<title>La Rede</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/estilo.css">

	</head>

	<body>

		<header>
	      <nav class="navbar navbar-expand-sm navbar-light fixed-top bg-warning">
	        <div class="container">
	          <a href="/" class="navbar-brand">
	            <i class="fab fa-accusoft fa-2x text-light"></i>
	          </a>
	          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
	            <!--<span class="navbar-toggler-icon"></span>-->
	            <i class="fas fa-bars text-white"></i>
	          </button>
	          <div id="nav-principal" class="collapse navbar-collapse">
	            <ul class="navbar-nav ml-auto">
	              <li class="nav-item">
	                <a href="/" class="nav-link">Home</a>
	              </li>
	              <li class="nav-item">
	                <a href="/error_notfound" class="nav-link">Recusos</a>
	              </li>
	              <li class="nav-item">
	                <a href="/error_notfound" class="nav-link">Beneficios</a>
	              </li>
	              <li class="nav-item">
	                <a href="/error_notfound" class="nav-link">Preços</a>
	              </li>
	              <li class="nav-item">
	                <a href="/login" class="btn btn-outline-light ml-4 d-none d-sm-block">Entrar</a>
	              </li>
	              <li class="nav-item">
	                <a href="/login" class="btn btn-outline-light d-sm-none">Entrar</a>
	              </li>
	              <li class="nav-item">
	                <a href="/inscreverse" class="btn btn-outline-light ml-4 d-none d-sm-block">Inscrever-se</a>
	              </li>
	              <li class="nav-item">
	                <a href="/inscreverse" class="btn btn-outline-light d-sm-none mt-2">Inscrever-se</a>
	              </li>
	            </ul>
	            
	          </div>
	        </div>
	      </nav>
	    </header>

		<?= $this->content() ?>

		<footer class="mt-4 mb-4">
	      <div class="container">
	        <div class="row">
	          <div class="col-md-8">
	            <p>
	              <a href="">Home</a>
	              <a href="">Recursos</a>
	              <a href="">Beneficios</a>
	              <a href="">Preços</a>
	            </p>
	          </div>
	          <div class="col-md-4 d-flex justify-content-end">
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-facebook"></i>
	            </a>
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-twitter"></i>
	            </a>
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-youtube"></i>
	            </a>
	          </div>
	        </div>
	      </div>
	    </footer>
	    
	</body>

</html>