<!DOCTYPE html>
	<html>
	<head>
		<title>Administrador</title>
		<meta charset="utf-8">

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/estilo.css">
	</head>
	<body>
		<!-- Cabeçalho -->
		<header>
	      <nav class="navbar navbar-expand-sm navbar-light fixed-top bg-primary">
	        <div class="container">
	          <a href="/dashboard" class="navbar-brand">
	            <i class="fab fa-accusoft fa-2x text-light"></i>
	          </a>
	          <div id="nav-principal" class="collapse navbar-collapse">
	            <ul class="navbar-nav ml-auto">
	              <li class="nav-item">
	                <a href="/dashboard" class="nav-link">Home</a>
	              </li>
	              <li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						|    Olá Sr. <?= $this->view->nome ?>
			        </a>
			        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			          <a class="dropdown-item text-danger" href="#">Editar perfil</a>
			          <a class="dropdown-item" href="/sair">Sair</a>
			        </div>
			       </li>
              	<div class="media align-self-center">
				  <img class="mr-3 ml-2 rounded-circle" style="width: 50px; height: 50px" src="<?= $this->view->imagem_perfil ?>">
				</div>
	            </ul>

	          </div>
	        </div>
	      </nav>
	    </header>


		<?= $this->content() ?>

		<footer class="mt-4 mb-4">
	      <div class="container">
	        <div class="row">
	          <div class="col-md-8">
	            <p>
	              <a href="/dashboard">Home</a>
	              <a href="#" class="text-danger">Recursos</a>
	              <a href="#" class="text-danger">Beneficios</a>
	              <a href="#" class="text-danger">Preços</a>
	            </p>
	          </div>
	          <div class="col-md-4 d-flex justify-content-end">
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-facebook"></i>
	            </a>
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-twitter"></i>
	            </a>
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-youtube"></i>
	            </a>
	          </div>
	        </div>
	      </div>
	    </footer>

	</body>
</html>