<!DOCTYPE html>
	<html>
	<head>
		<title>Corretor</title>
		<meta charset="utf-8">

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/estilo.css">
	</head>
	<body>
		<header>
	      <nav class="navbar navbar-expand-sm navbar-light fixed-top bg-success">
	        <div class="container">
	          <a href="/dashboardC" class="navbar-brand">
	            <i class="fab fa-accusoft fa-2x text-light"></i>
	          </a>
	          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
	            <!--<span class="navbar-toggler-icon"></span>-->
	            <i class="fas fa-bars text-white"></i>
	          </button>
	          <div id="nav-principal" class="collapse navbar-collapse">
	            <ul class="navbar-nav ml-auto">
	              <li class="nav-item">
	                <a href="" class="nav-link">Home</a>
	              </li>
	              <li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          Modulo
			        </a>
			        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			          <a class="dropdown-item" href="#">Comprador/Vendedor</a>
			          <a class="dropdown-item" href="#">Corretor</a>
			      </li>
	              <li class="nav-item">
	                <a href="" class="nav-link">Editar perfil</a>
	              </li>
	              <li class="nav-item">
	              <li class="nav-item">
	                <a href="" class="nav-link">Sair</a>
	              </li>
	            </ul>
	            
	            <span class="navbar-text ml-2">
				  | Olá Sra. Miranda! 
				</span>
              	<div class="media align-self-center">
				  <img class="mr-3 ml-2 rounded-circle" style="widows: 50px; height: 50px" src="img/miranda_teles.jpeg">
				</div>
                <a href="" class="btn btn-outline-light d-sm-none">Entrar</a>
	            
	          </div>
	        </div>
	      </nav>
	    </header>

		<?php $this->content(); ?>

		<footer class="mt-4 mb-4">
	      <div class="container">
	        <div class="row">
	          <div class="col-md-8">
	            <p>
	              <a href="/">Home</a>
	              <a href="/error_notfound">Recursos</a>
	              <a href="/error_notfound">Beneficios</a>
	              <a href="/error_notfound">Preços</a>
	            </p>
	          </div>
	          <div class="col-md-4 d-flex justify-content-end">
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-facebook"></i>
	            </a>
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-twitter"></i>
	            </a>
	            <a href="" class="btn btn-outline-dark ml-2">
	              <i class="fab fa-youtube"></i>
	            </a>
	          </div>
	        </div>
	      </div>
	    </footer>
	    
	</body>
</html>