  <body>
    <section style="padding-top: 66px">
      <div class="jumbotron container text-center">
        <div class="card-columns">
          <div class="container">
          
          <a href="/imoveis_pendentes">
            <div id="caixa" class="card">
              <div class="card-body">                
                <div class="card-title text-dark">
                  Imóveis Pendentes
                  <span class="badge badge-primary"><?= $this->view->qtdImoveisPendentes ?></span>
                </div>
              </div>
            </div>
          </a>  

            <div id="caixa" class="card">
              <div class="card-body">
                <div class="card-title text-danger">Visitas Marcadas
                  <span class="badge badge-primary">13</span>
                </div>
              </div>
            </div>
            
            <a href="/gerenciar_corretores">
            <div class="card">
              <div class="card-body">
                <div class="card-title text-dark">Gerenciar Corretores</div>
              </div>
            </div>
            </a>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Gerenciar Usuários</div>
              </div>
            </div>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Solicitações de Usuários
                  <span class="badge badge-primary">2</span>
                </div>
              </div>
            </div>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Mais Opções</div>
              </div>
            </div>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Imagens Carrousel</div>
              </div>
            </div>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Todos os Imoveis</div>
              </div>
            </div>

            <a href="/imoveis_home">
            <div class="card">
              <div class="card-body">
                <div class="card-title text-dark">Imóveis Página Inicial</div>
              </div>
            </div>
            </a>

          </div>
        </div>
      </div>
    </section>
  </body>