<section style="padding-top: 80px;" class="container">
	<h3>Avaliar Imovel</h3>
</section>

<section>

  <div class="container jumbotron" style="border-color: black">
    <section class="mb-5">
    <!-- Carousel -->
    <div id="carousel-controles" class="carousel slide bg-dark container" data-ride="carousel">

       <!-- Indicadores -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-controles" data-slide-to="0"></li>
        <li data-target="#carousel-controles" data-slide-to="1"></li>
        <li data-target="#carousel-controles" data-slide-to="2"></li>
      </ol>

        <!-- Inner -->
      <div class="carousel-inner" style="text-align: center;">
        <div class="carousel-item active">
          <img src="img/carousel/imagem1.jpeg" class="img-fluid">
          <div class="carousel-caption">
            <h3>Item 1</h3>
            <p>Lorem Ipsum</p>
          </div>
        </div>

        <div class="carousel-item">
          <img src="img/carousel/imagem2.jpeg" class="img-fluid">
        </div>

        <div class="carousel-item">
          <img src="img/carousel/imagem3.jpeg" class="img-fluid">
        </div>
      </div>

      <!-- Controles -->
      <a href="#carousel-controles" class="carousel-control-prev" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>

      <a href="#carousel-controles" class="carousel-control-next" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>

    </div>
    </section>
    <div>
      <div class="row mb-5">
        <div class="col-lg-6">
          <h5>Proprietário: <?= $this->view->imovel['nome'] ?></h5>
          <h5>Tipo do imóvel: <?= $this->view->imovel['tipo'] ?></h5>
          <h5>Status: <?= $this->view->imovel['status'] ?></h5>
        </div>
        <div class="col-lg-6">
          <h5>Endereço: <?= $this->view->imovel['endereco'] ?></h5>
          <h5>Número: <?= $this->view->imovel['numero'] ?></h5>
          <h5>Bairro: <?= $this->view->imovel['bairro'] ?></h5>
          <h5>CEP: <?= $this->view->imovel['cep'] ?></h5>
        </div>
      </div>

      <div class="row mb-5">
        <div class="col-lg-6">
          <h5>Área útil: <?= $this->view->imovel['area_util'] ?></h5>
          <h5>Área total: <?= $this->view->imovel['area_total'] ?></h5>
        </div>

        <div class="col-lg-6">
          <h5>Qtd. quartos: <?= $this->view->imovel['quartos'] ?></h5>
          <h5>Qtd. banheiros: <?= $this->view->imovel['banheiros'] ?></h5>
          <h5>Qtd. garagens: <?= $this->view->imovel['garagens'] ?></h5>
          <h5>Qtd. suítes: <?= $this->view->imovel['suites'] ?></h5>
        </div>
      </div>

      <div class="row">
      <div class="col-lg-6">
        <div class="row">
          <h5 class="container">Descriçãodo imóvel: </h5>  
        </div>
        <div class="row container jumbotron border border-dark">
          <?= $this->view->imovel['tipo'] ?>
        </div>      
      </div>
      <div class="col-lg-6">
        <h4>Valor: R$<?= $this->view->imovel['valor'] ?></h4>
      </div>
      </div>
      <div class="clearfix">
      <div class="row float-right">
        <a class="btn btn-success btn-lg" href="/acao_imovel?acao=validar_imovel&id_imovel=<?= $this->view->imovel['id'] ?>" role="button">Validar</a>
      </div>
      </div>
    </div>
    
  </div>

<!-- Tabela Corretores-->
</section>
<section class="container">

<?php $this->view->n = 1 ?>
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">Responsável</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->view->corretores as $indice_arr => $corretor) { ?>
      <tr>
        <th scope="row"><?= $this->view->n++ ?></th>
        <td><?= $corretor['nome'] ?></td>
        <td><?= $corretor['email'] ?></td>
        <td>
          <?php if($corretor['id'] != $this->view->imovel['corretor_responsavel'] ){ ?>
            <a class="btn btn-success" href="/acao_imovel?acao=set_corretor&id_c=<?= $corretor['id'] ?>&id_imovel=<?= $this->view->imovel['id'] ?>" role="button">Marcar como responsavel</a>
          <?php } ?>

          <?php if($corretor['id'] == $this->view->imovel['corretor_responsavel'] ){ ?>
            <a class="btn btn-danger" href="/acao_imovel?acao=unset_corretor&id_imovel=<?= $this->view->imovel['id'] ?>" role="button">Desmarcar como responsavel</a>
          <?php } ?>
        </td>
      </tr>
    <?php } ?>
    
  </tbody>
</table>

</section>