<section style="padding-top: 5em">
<div class="container jumbotron">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="https://source.unsplash.com/random/400x200"/>
        </div>

        <div class="row">
          <div class="col">
            <h2 class="text-center">Cadastro realizado com sucesso</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/login" class="btn btn-warning btn-block">Clique aqui para fazer login!</a>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col">
            <a href="/" class="btn btn-warning btn-block">Página Inicial</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
</section> 
  