<section style="background: #EEEDE2">
<div class="container" style="margin-top: 10em; padding: 2em">

	<div class="row d-flex" style="padding:  1em; margin-left: 10em">
		<div class="col-1">
			<i class="fas fa-bug fa-3x"></i>
		</div>
		<div class="ml-3">
			<h1>Desculpe!</h1>
		</div>
	</div>

	<div class="row d-flex" style="padding:  1em; margin-left: 10em">
		<div class="col-1">
			<i class="fas fa-people-carry fa-3x"></i>
		</div>
		<div class="ml-3">
			<h6>Página em Construção. Estamos trabalhando para levar o melhor até você! :)</h6>
		</div>
	</div>

	<div class="row d-flex" style="padding:  1em; margin-left: 10em">
		<div class="col-1">
			<i class="fas fa-search fa-3x"></i>
		</div>
		<div class="ml-3">
			<h6>Enquanto isso, explore outras funcionalidade!</h6>
		</div>
	</div>

	<div class="row d-flex justify-content-center">
		<a href="/" class="btn btn-outline-warning text-dark btn-lg mr-3">Home</a>
		<a href="/login" class="btn btn-outline-warning text-dark btn-lg">Login</a>
		<a href="/inscreverse" class="btn btn-outline-warning text-dark btn-lg ml-3">Inscreva-se</a>
	</div>

</div>
</section>