<div class="Jumbotron Container">
	<div class="card">
		<form action="/upar_imagem" method="post" enctype="multipart/form-data">
		  <div class="form-group">
		    <label for="exampleFormControlFile1">Example file input</label>
		    <input type="file" name="imagem" class="form-control-file" id="exampleFormControlFile1">
		  </div>
		  <button type="submit" class="btn btn-primary" accept="image/png, image/jpeg">Submit</button>
		</form>
	</div>
</div>