  <body>
    <!-- Cabeçalho -->
    <header>
      <nav class="navbar navbar-expand-sm navbar-light fixed-top bg-warning">
        <div class="container">
          <a href="index.html" class="navbar-brand">
            <i class="fab fa-accusoft fa-2x text-light"></i>
          </a>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <!--<span class="navbar-toggler-icon"></span>-->
            <i class="fas fa-bars text-white"></i>
          </button>
          <div id="nav-principal" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a href="" class="nav-link">Home</a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">Recusos</a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">Beneficios</a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">Preços</a>
              </li>
              <li class="nav-item">
                <a href="/login" class="btn btn-outline-light ml-4 d-none d-sm-block">Entrar</a>
              </li>
              <li class="nav-item">
                <a href="/login" class="btn btn-outline-light d-sm-none">Entrar</a>
              </li>
            </ul>
            
          </div>
        </div>
      </nav>
    </header>

    <section style="padding-top: 66px; background: yellow;">
    <!-- Carousel -->
    <div id="carousel-controles" class="carousel slide bg-dark" data-ride="carousel">

       <!-- Indicadores -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-controles" data-slide-to="0"></li>
        <li data-target="#carousel-controles" data-slide-to="1"></li>
        <li data-target="#carousel-controles" data-slide-to="2"></li>
      </ol>

        <!-- Inner -->
      <div class="carousel-inner" style="text-align: center;">
        <div class="carousel-item active">
          <img src="img/carousel/imagem1.jpeg" class="img-fluid">
          <div class="carousel-caption">
            <h3>Item 1</h3>
            <p>Lorem Ipsum</p>
          </div>
        </div>

        <div class="carousel-item">
          <img src="img/carousel/imagem2.jpeg" class="img-fluid">
        </div>

        <div class="carousel-item">
          <img src="img/carousel/imagem3.jpeg" class="img-fluid">
        </div>
      </div>

      <!-- Controles -->
      <a href="#carousel-controles" class="carousel-control-prev" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>

      <a href="#carousel-controles" class="carousel-control-next" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>

    </div>
    </section>

    <!-- Início de sessão Cards-->
      <div class="card-columns container">

        <?php foreach ($this->view->imoveis as $key => $value) {?>

          <div class="card border-primary">
            <img class="card-img-top" src="https://source.unsplash.com/random/400x200">
            <div class="card-body">
              <h4 class="card-title"><?= $value['endereco'] ?></h4>
              <h6 class="card-subtitle"><?= $value['bairro'] ?></h6>
              <h6>R$ <?= $value['valor'] ?></h6>

              <div class="row" style="padding-top: 1em">
                <div class="col">
                  <div class="row d-flex justify-content-center">
                    <i class="fas fa-2x fa-vector-square"></i>
                  </div>
                  <div class="row d-flex justify-content-center">
                    <?= $value['area_util'] ?>m²
                  </div>
                </div>

                <div class="col">
                  <div class="row d-flex justify-content-center">
                    <i class="fas fa-2x fa-bath"></i>
                  </div>
                  <div class="row d-flex justify-content-center">
                    <?= $value['banheiros'] ?> Banheiro(s)
                  </div>                
                </div>

                <div class="col">
                  <div class="row d-flex justify-content-center">
                    <i class="fas fa-2x fa-bed"></i>
                  </div>
                  <div class="row d-flex justify-content-center">
                    <?= $value['quartos'] ?> Quarto(s)
                  </div>  
                </div>
              </div>
              <div class="d-flex justify-content-end" style="padding-top: 1em">
                <a href="" class="btn btn-outline-primary">Mais informações</a>
              </div>
            </div>
          </div>
        <?php } ?>
        </div>




    <!-- Início de sessão Dr. Sales-->
    <section class="caixa">
      <div class="container">
        <div class="row">
          <div class="col-md-6 d-flex justify-content-center">
            <div class="align-self-center">
              <h2>Dr. Alisson Sales</h2>
              <p>Otimo sistema para vender imóveis!</p>
            </div>
          </div>
          <div class="col-md-6 d-flex justify-content-center">
            <img src="img/alisson_sales.jpeg" class="rounded-circle w-25">
          </div>
        </div>
      </div>
    </section>

    <!-- Início de sessão Sra. Miranda Teles-->
    <section class="caixa">
      <div class="container">
        <div class="row">
          <div class="col-md-6 d-flex justify-content-center">
            <img src="img/miranda_teles.jpeg" class="rounded-circle w-25">
          </div>
          <div class="col-md-6 d-flex justify-content-center">
            <div class="align-self-center">
              <h2>Sra. Miranda Teles</h2>
              <p>Otimo sistema para vender imóveis!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Início de sessão Dr. Ruth Silva-->
    <section class="caixa">
      <div class="container">
        <div class="row">
          <div class="col-md-6 d-flex justify-content-center">
            <div class="align-self-center">
              <h2>Dr. Ruth Silva</h2>
              <p>Otimo sistema para vender imóveis!</p>
            </div>
          </div>
          <div class="col-md-6 d-flex  justify-content-center">
            <img src="img/ruth_silva.jpeg" class="rounded-circle w-25">
          </div>
        </div>
      </div>
    </section>

    <!-- Início de sessão três colunas -->
    <section class="caixa">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="d-flex justify-content-center">
              <img src="img/facil.png" class="w-75 p-3 align-self-center">
            </div>
            <div class="d-flex  justify-content-center">
              <h2>Fácil de usar</h2>
            </div>
          </div>
          <div class="col-md-4">
            <div class="d-flex justify-content-center">
              <img src="img/economize.png" class="w-75 p-3 align-self-center">
            </div>
            <div class="d-flex justify-content-center">
              <h2>Economize seu tempo</h2>
            </div>
          </div>
          <div class="col-md-4">
            <div class="d-flex justify-content-center">
              <img src="img/suporte.png" class="w-75 p-3 align-self-center">
            </div>
            <div class="d-flex justify-content-center">
              <h2>Suporte amigo</h2>
            </div>
          </div>
        </div>
      </div>
    </section>

    <footer class="mt-4 mb-4">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <p>
              <a href="">Home</a>
              <a href="">Recursos</a>
              <a href="">Beneficios</a>
              <a href="">Preços</a>
            </p>
          </div>
          <div class="col-md-4 d-flex justify-content-end">
            <a href="" class="btn btn-outline-dark ml-2">
              <i class="fab fa-facebook"></i>
            </a>
            <a href="" class="btn btn-outline-dark ml-2">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="btn btn-outline-dark ml-2">
              <i class="fab fa-youtube"></i>
            </a>
          </div>
        </div>
      </div>
    </footer>