<div class="container">
  <div class="d-flex justify-content-center" style="padding: 7em">
    <div class="card" style="width: 36rem;">
      <div class="card-body">


        <div class="row" style="padding-bottom: 3em">
          <div class="col">
            <h2 class="text-center">Login</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/autenticar" method="post">
              
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email'] ?>"name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['senha'] ?>"name="senha" class="form-control" placeholder="Senha">
              </div>
              <button type="submit" class="btn btn-warning btn-block">Aceder</button>
              <?php if($this->view->login == 'erro') {?>
              <div class="row">
                <div class="col">
                  <span class="text text-danger">*E-mail e ou senha inválido(s)</span>
                </div>
              </div>
              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>