 <body>
    <section style="padding-top: 66px">
      <div class="jumbotron container text-center">
        <div class="card-columns">
          <div class="container">
          
          <a href="">
            <div class="card">
              <div class="card-body">                
                <div class="card-title text-dark">
                  Corretor
                  <span class="badge badge-primary">14</span>
                </div>
              </div>
            </div>
          </a>  

             <div class="card">
              <div class="card-body">
                <div class="card-title">Comprador/Vendedor
                  <span class="badge badge-primary">13</span>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
</body>