<div class="jumbotron container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 90rem;">
      <div class="card-body">

        <div class="row">
          <div class="col">
            <h2 class="text-center mb-5">cadastre seu imóvel</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="#" method="post">
              <div class="form-group row">
                <label class="col-lg-3">Tipo do imóvel</label>
                <div class="col-lg-9">
                  <select class="form-control">
                    <option>Apartamento</option>
                    <option>Casa</option>
                    <option>Terreno</option>
                  </select>
                </div>
              </div>

              <div class="form-group row">
                <label class="col-lg-3">CEP</label>
                <div class="col-lg-9">
                  <input name="cep" class="form-control" placeholder="______-__">
                </div>
              </div>
              
              <div class="form-group row">
                <label class="col-lg-3">Endereço</label>
                <div class="col-lg-9">
                  <input name="endereco" class="form-control" placeholder="Ex.: Rua Mont Alverne">
                </div>
              </div>

              <div class="form-group row">
                  <label class="col-lg-3">Número</label>
                  <div class="col-lg-3">
                    <input name="endereco" class="form-control" placeholder="1234">
                  </div>

                  <label class="col-lg-2">Bairro</label>
                  <div class="col-lg-4">
                    <input name="endereco" class="form-control">
                  </div>
              </div>

            </div>

            <div class="col">
              
              <div class="form-group row">
                <label class="col-lg-2">Área útil</label>
                <div class="col-lg-4">
                  <input name="endereco" class="form-control" placeholder="m²">
                </div>
                <label class="col-lg-2">Área total</label>
                <div class="col-lg-4">
                  <input name="endereco" class="form-control" placeholder="m²">
                </div>
              </div>

              <div class="form-group row">
                <label class="col-lg-3">Tipo de Negócio</label>
                <div class="col-lg-9">
                  <select class="form-control">
                    <option>Aluguel</option>
                    <option>Venda</option>
                    <option>Temporada</option>
                  </select>
                </div>
              </div>
              
              <div class="form-group">
                <input type="date" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <label for="areaTexto">Descrição do Imóvel</label>
                <textarea class="form-control" id="areaTexto" rows="3"></textarea>
              </div>
            </div>
            </div>
              
              <button type="submit" class="btn btn-warning btn-block">Inscrever-se</button>
              <?php if($this->view->erroCadastro) { ?>
                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente</small>
              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>