<div class="jumbotron container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 90rem;">
      <div class="card-body" style="padding: 3em">

        <div class="row">
          <div class="col">
            <h2 class="text-center mb-5">cadastre seu imóvel</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="/registrarImovel" method="post" encType="multipart/form-data">

              <div class="form-group row">
                <label for="exampleFormControlFile1">Example file input</label>
                <input name="imagens" accept="image/*" class="file-chooser" type="file" class="form-control-file" id="exampleFormControlFile1">
                <div class="media align-self-center jumbotron col-lg-12">
                  <img class="preview-img" style="widows: 100px; height: 100px">
                </div>
              </div>

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="tipoImovel">Tipo do imóvel</label>
                  <select name="tipoImovel" class="form-control col-lg-9" id="tipoImovel">
                    <option>Apartamento</option>
                    <option>Casa</option>
                    <option>Terreno</option>
                  </select>
              </div>

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="cep">CEP</label>
                  <input id="cep" name="cep" class="form-control col-lg-9" placeholder="______-__">
              </div>

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="cidade">Cidade</label>
                  <input name="cidade" class="form-control col-lg-9" id="cidade">
              </div>
              
              <div class="form-group row">
                <label class="col-lg-3 text-right">Endereço</label>
                  <input name="endereco" class="form-control col-lg-9" placeholder="Ex.: Rua Mont Alverne">
              </div>

              <div class="form-group row">
                  <label class="col-lg-3 text-right" id="numero">Número</label>
                    <input name="numero" class="form-control col-lg-3" id="numero" placeholder="1234">

                  <label class="col-lg-2 text-right" for="bairro">Bairro</label>
                    <input name="bairro" class="form-control col-lg-4" id="bairro">
              </div>

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="valor">Valor</label>
                  <input name="valor" class="form-control col-lg-9" id="valor" placeholder="R$">
              </div>

            </div>

            <div class="col">
              
              <div class="form-group row">
                <label class="col-lg-2 text-right" for="areaUtil">Área útil</label>
                  <input name="areaUtil" class="form-control col-lg-4" id="areaUtil" placeholder="m²">

                <label class="col-lg-2 text-right" for="areaTotal">Área total</label>
                  <input name="areaTotal" class="form-control col-lg-4" id="areaTotal" placeholder="m²">
              </div>

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="tNegocio">Tipo de Negócio</label>
                  <select name="tipoNegocio" class="form-control col-lg-9" id="tNegocio">
                    <option>Aluguel</option>
                    <option>Venda</option>
                    <option>Temporada</option>
                  </select>
              </div>

              <div class="form-group row">
                  <label class="col-lg-3 text-right" id="numero">Quartos</label>
                    <select name="quartos" class="col-lg-3 form-control" id="tNegocio">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                  </select>

                  <label class="col-lg-3 text-right" for="bairro">Banheiros</label>
                    <select name="banheiros" class="col-lg-3 form-control" id="tNegocio">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                  </select>
              </div>

              <div class="form-group row">
                  <label class="col-lg-3 text-right" id="numero">Garagens</label>
                    <select name="garagens" class="col-lg-3 form-control" id="tNegocio">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                  </select>

                  <label class="col-lg-3 text-right" for="bairro">Suítes</label>
                    <select name="suites" class="col-lg-3 form-control" id="tNegocio">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                  </select>
              </div>

              <div class="form-group">
                <label for="areaTexto">Descrição do Imóvel</label>
                <textarea name="descricao" class="form-control" id="areaTexto" rows="3"></textarea>
              </div>
            </div>
            </div>
              
              <button type="submit" class="btn btn-warning btn-block mt-5">Cadastrar Imóvel</button>
              <?php if($this->view->erroCadastro) { ?>
                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente</small>
              <?php } ?>
            </form>
            <script>
              const $ = document.querySelector.bind(document);
              const previewImg = $('.preview-img');
              const fileChooser = $('.file-chooser');
              fileChooser.onchange = e => {
                const fileToUpload = e.target.files.item(0);
                const reader = new FileReader();

                // evento disparado quando o reader terminar de ler 
                reader.onload = e => previewImg.src = e.target.result;

                // solicita ao reader que leia o arquivo 
                // transformando-o para DataURL. 
                // Isso disparará o evento reader.onload.
                reader.readAsDataURL(fileToUpload);
              };
            </script>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>