<div class="jumbotron container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 90rem;">
      <div class="card-body" style="padding: 3em">

          <small class="text-danger">*Para cadastrar um imóvel, precisamos de algumas informações a respeito do proprietário</small>
        <div class="row">
          <div class="col">
            <h2 class="text-center mb-5">Informações sobre proprietário</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="/registrarProprietario" method="post">

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="cep">CEP</label>
                  <input id="cep" name="cep" class="form-control col-lg-9" placeholder="______-__">
              </div>

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="uf">Estado</label>
                  <select class="form-control col-lg-9" id="uf">
                    <option value="AC">Acre</option>
                    <option value="AL">Alagoas</option>
                    <option value="AP">Amapá</option>
                    <option value="AM">Amazonas</option>
                    <option value="BA">Bahia</option>
                    <option value="CE">Ceará</option>
                    <option value="DF">Distrito Federal</option>
                    <option value="ES">Espírito Santo</option>
                    <option value="GO">Goiás</option>
                    <option value="MA">Maranhão</option>
                    <option value="MT">Mato Grosso</option>
                    <option value="MS">Mato Grosso do Sul</option>
                    <option value="MG">Minas Gerais</option>
                    <option value="PA">Pará</option>
                    <option value="PB">Paraíba</option>
                    <option value="PR">Paraná</option>
                    <option value="PE">Pernambuco</option>
                    <option value="PI">Piauí</option>
                    <option value="RJ">Rio de Janeiro</option>
                    <option value="RN">Rio Grande do Norte</option>
                    <option value="RS">Rio Grande do Sul</option>
                    <option value="RO">Rondônia</option>
                    <option value="RR">Roraima</option>
                    <option value="SC">Santa Catarina</option>
                    <option value="SP">São Paulo</option>
                    <option value="SE">Sergipe</option>
                    <option value="TO">Tocantins</option>
                  </select>
              </div>

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="cidade">Cidade</label>
                  <input name="cidade" class="form-control col-lg-9" id="cidade">
              </div>
              
              <div class="form-group row">
                <label class="col-lg-3 text-right">Endereço</label>
                  <input name="endereco" class="form-control col-lg-9" placeholder="Ex.: Rua Mont Alverne">
              </div>

              <div class="form-group row">
                  <label class="col-lg-3 text-right" id="numero">Número</label>
                    <input name="numero" class="form-control col-lg-3" id="numero" placeholder="1234">

                  <label class="col-lg-2 text-right" for="bairro">Bairro</label>
                    <input name="bairro" class="form-control col-lg-4" id="bairro">
              </div>


            </div>

            <div class="col">

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="cep">CPF</label>
                  <input id="cpf" name="cpf" class="form-control col-lg-9" placeholder="000.000.000-00">
              </div>

              <div class="form-group row">
                <label class="col-lg-3 text-right" for="cidade">CNPJ</label>
                  <input name="cnpj" class="form-control col-lg-9" id="cnpj" placeholder="00.000.000/000-00">
              </div>
            </div>
              
              <button type="submit" class="btn btn-warning btn-block mt-5">Salvar Proprietario</button>
              <?php if($this->view->erroCadastro) { ?>
                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente</small>
              <?php } ?>
            </form>
            <script type="text/javascript">
              $('#cep').mask('00000-000');
              $('#cpf').mask('000.000.000-00', {reverse: true});
              $('#cnpj').mask('00.000.000/0000-00', {reverse: true});

              $("#cep").focusout(function(){
              //Início do Comando AJAX
              $.ajax({
                //O campo URL diz o caminho de onde virá os dados
                //É importante concatenar o valor digitado no CEP
                url: 'https://viacep.com.br/ws/'+$(this).val()+'/json/unicode/',
                //Aqui você deve preencher o tipo de dados que será lido,
                //no caso, estamos lendo JSON.
                dataType: 'json',
                //SUCESS é referente a função que será executada caso
                //ele consiga ler a fonte de dados com sucesso.
                //O parâmetro dentro da função se refere ao nome da variável
                //que você vai dar para ler esse objeto.
                success: function(resposta){
                  //Agora basta definir os valores que você deseja preencher
                  //automaticamente nos campos acima.
                  $("#endereco").val(resposta.logradouro);
                  //$("#complemento").val(resposta.complemento);
                  $("#bairro").val(resposta.bairro);
                  $("#uf").val(resposta.uf);
                  $("#cidade").val(resposta.localidade);
                  //Vamos incluir para que o Número seja focado automaticamente
                  //melhorando a experiência do usuário
                  $("#numero").focus();
                }
              });
            });
            </script>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>