<section style="padding-top: 80px;" class="container">
	<h3>Avaliar Imovel</h3>
</section>

<section>

  <div class="container jumbotron" style="border-color: black">
    
    <section class="mb-5">
    <?php $count = count($this->view->imagens) ?> 
    <!-- Carousel -->
    <div id="carousel-controles" class="carousel slide bg-dark container" data-ride="carousel">

       <!-- Indicadores -->
      <ol class="carousel-indicators">
        <?php for ($i=0; $i < $count; $i++) { ?>
          <li data-target="#carousel-controles" data-slide-to="<?= $i ?>"></li>
        <?php } ?>
        <!--<li data-target="#carousel-controles" data-slide-to="1"></li>
        <li data-target="#carousel-controles" data-slide-to="2"></li>-->
      </ol>

      <!-- Inner -->
      <div class="carousel-inner" style="text-align: center; height: 30em">
        <div class="carousel-item active">
            <img style="height: 30em" src="<?= $this->view->imagens[0]['imagem'] ?>" class="img-fluid">
        </div>
        <?php for ($i=1; $i < $count ; $i++) { ?>
          <div class="carousel-item">
            <img style="height: 30em" src="<?= $this->view->imagens[$i]['imagem'] ?>" class="img-fluid">
          </div>
        <?php } ?>

        <!--<div class="carousel-item">
          <img src="img/carousel/imagem2.jpeg" class="img-fluid">
        </div>

        <div class="carousel-item">
          <img src="img/carousel/imagem3.jpeg" class="img-fluid">
        </div>-->
      </div>

      <!-- Controles -->
      <a href="#carousel-controles" class="carousel-control-prev" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>

      <a href="#carousel-controles" class="carousel-control-next" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>

    </div>
    </section>

    <div>
      <div class="row mb-5">
        <div class="col-lg-6">
          <h5>Tipo do imóvel: <?= $this->view->imovel['tipo'] ?></h5>
        </div>
        <div class="col-lg-6">
          <h5>Endereço: <?= $this->view->imovel['endereco'] ?></h5>
          <h5>Número: <?= $this->view->imovel['numero'] ?></h5>
          <h5>Bairro: <?= $this->view->imovel['bairro'] ?></h5>
          <h5>CEP: <?= $this->view->imovel['cep'] ?></h5>
        </div>
      </div>

      <div class="row mb-5">
        <div class="col-lg-6">
          <h5>Área útil: <?= $this->view->imovel['area_util'] ?>m²</h5>
          <h5>Área total: <?= $this->view->imovel['area_total'] ?>m²</h5>
        </div>

        <div class="col-lg-6">
          <h5>Qtd. quartos: <?= $this->view->imovel['quartos'] ?></h5>
          <h5>Qtd. banheiros: <?= $this->view->imovel['banheiros'] ?></h5>
          <h5>Qtd. garagens: <?= $this->view->imovel['garagens'] ?></h5>
          <h5>Qtd. suítes: <?= $this->view->imovel['suites'] ?></h5>
        </div>
      </div>

      <div class="row">
      <div class="col-lg-6">
        <div class="row">
          <h5 class="container">Descriçãodo imóvel: </h5>  
        </div>
        <div class="row container jumbotron border border-dark">
          <?= $this->view->imovel['tipo'] ?>
        </div>      
      </div>
      <div class="col-lg-6">
        <h4>Valor: R$<?= $this->view->imovel['valor'] ?></h4>
      </div>
      </div>
      <div class="clearfix">
      <div class="row float-right">
        <a class="btn btn-success btn-lg" href="/timeline" role="button">Tenho interesse!</a>
      </div>
      </div>
    </div>
    
  </div>